default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%=  ENV["POSTGRES_PASSWORD"] %>
  pool: 5
  variables:
    statement_timeout: 5000
development:
  <<: *default
  database: myapp_development
test:
  <<: *default
  database: myapp_test
production:
  <<: *default
  database: myapp_production
